apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: zubair280/notes-backend:latest
        ports:
        - containerPort: 3000  # Correct container port
        env:
        - name: MONGODB_URI
          value: mongodb://mongo-service:27017/notes-app
        - name: CORS_ORIGIN
          value: "*"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 3000  # Change service port to match container port
      targetPort: 3000