name: Build and Deploy to Minikube

on:
  push:
    branches: 
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker to use Minikube's environment
      shell: powershell
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        # This is the Windows PowerShell equivalent of eval $(minikube docker-env)
        & minikube -p minikube docker-env | Invoke-Expression
        
    - name: Build and push frontend image
      shell: powershell
      run: |
        cd frontend
        docker build -t zubair280/notes-frontend:latest .
        
    - name: Build and push backend image
      shell: powershell
      run: |
        cd server
        docker build -t zubair280/notes-backend:latest .
        
    - name: Login to Docker Hub
      shell: powershell
      run: |
        $password = "${{ secrets.DOCKER_PASSWORD }}"
        docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "$password"
      
    - name: Push Docker images to Docker Hub
      shell: powershell
      run: |
        docker push zubair280/notes-frontend:latest
        docker push zubair280/notes-backend:latest
        
    - name: Create namespace if not exists
      shell: powershell
      run: |
        $namespaceExists = kubectl get namespace notes-app
        if ($LASTEXITCODE -ne 0) {
          Write-Output "Creating namespace notes-app..."
          kubectl create namespace notes-app
        } else {
          Write-Output "Namespace notes-app already exists"
        }
        
    - name: Deploy to Minikube
      shell: powershell
      run: |
        kubectl apply -f mongodb.yaml -n notes-app
        kubectl apply -f nginx-config.yaml -n notes-app
        kubectl apply -f backend.yaml -n notes-app
        kubectl apply -f frontend.yaml -n notes-app
        
    - name: Verify deployment
      shell: powershell
      run: |
        kubectl get pods -n notes-app
        echo "Deployment completed successfully!"