name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)
        
    - name: Build and push frontend image
      run: |
        cd frontend
        docker build -t zubair280/notes-frontend:latest .
        
    - name: Build and push backend image
      run: |
        cd server
        docker build -t zubair280/notes-backend:latest .
        
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Push Docker images to Docker Hub
      run: |
        docker push zubair280/notes-frontend:latest
        docker push zubair280/notes-backend:latest
        
    - name: Deploy to Minikube
      run: |
        kubectl apply -f mongodb.yaml -n notes-app
        kubectl apply -f nginx-config.yaml -n notes-app
        kubectl apply -f backend.yaml -n notes-app
        kubectl apply -f frontend.yaml -n notes-app
        
    - name: Verify deployment
      run: |
        kubectl get pods -n notes-app
        echo "Deployment completed successfully!"